[License_Key]
key = None

[Key_Map]
open_bag = 0
tab_rod = 1
rod = 2
fishing = 3
store_fish = 4
confirm = 5
jump = space
rodpos = 5

[adb]
bagx = 1200
bagy = 400
toolx = 950
tooly = 50
rod1x = 980
rod1y = 600
fishx = 1020
fishy = 420
storex = 1000
storey = 570
confirmx = 640
confirmy = 550
jumpx = 1100
jumpy = 570

[build]
build = bocui-vi

[User_Name]
username = Conan7901

